server:
  # 服务器的HTTP端口，默认为8080
  port: 8000
  servlet:
    # 应用的访问路径
    context-path: /api

mybatis-flex:
  # 数据源配置
  datasource:
    # 主库数据源
    master:
      url: jdbc:mysql://localhost:3306/wb-dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username:
      password:
      # 初始连接数
      initial-size: 5
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 5
      # 配置获取连接等待超时的时间（毫秒）
      max-wait: 60000
      # 是否缓存，对支持游标的数据库性能提升巨大
      pool-prepared-statements: false
      # 配置检测连接是否有效
      validation-query:
      # 配置检测连接是否有效的超时时间（秒）
      validation-query-timeout: 5
      # 申请连接时执行检测
      test-on-borrow: false
      # 归还连接时执行检测
      test-on-return: false
      # 申请连接时检测，如果空闲时间大于 time-between-eviction-runs-millis 则执行检测
      test-white-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间（毫秒）
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间（毫秒）
      max-evictable-idle-time-millis: 900000

# 日志配置
logging:
  level:
    com.wangboot: debug

# 应用配置
app:
  namespace: wangboot
  secret: abcdefghijklmnopqrstuvwxyz
  debug: true
  timezone: Asia/Shanghai
  captcha:
    enabled: false
    image:
      enabled: true
  # 接口加密配置
  crypto:
    enabled: false

# 管理端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: health,prometheus
  metrics:
    tags:
      application: wangboot

dromara:
  # 文件存储配置
  x-file-storage:
    # 默认使用的存储平台
    default-platform: local-plus-1
    # 缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".min.jpg"
    # 对应平台的配置写在这里，注意缩进要对齐
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  # 启用存储
        enable-access: true # 启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://127.0.0.1:8080/file/ # 访问域名，例如：“http://127.0.0.1:8030/file/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /file/** # 访问路径
        storage-path: ./data # 存储路径
